server:
    port: 8080
spring:
    datasource:
        driverClassName: org.h2.Driver
        password: pass
        url: jdbc:h2:file:/data/demo
        username: user
    # datasource:
    #     password: mypassword
    #     url: jdbc:mysql://localhost:3306/mydatabase
    #     username: user
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    security:
        user:
            name: user
            password: pass